-----AGGREGATE  FUNCTIONS AND GROUP BY----
--Bunun için databases kýsmýna sað klik restore database device ve yüklemek istediðimiz veri dosyasýný import edelim

--SQL'deki "Aggregate Functions" (Toplama Fonksiyonlarý), bir grup veri üzerinde bir iþlem uygulayarak 
--tek bir sonuç üreten fonksiyonlardýr. (SUM, MÝN, MAX, COUNT, AVG)

SELECT COUNT (*) AS SATIRSAYISI,  SUM(TOTALPRICE) AS CÝRO, SUM(AMOUNT) AS TOPLAMADET, 
MIN(PRICE) AS ENDUSUKFIYAT, MAX(PRICE) AS ENYUKSEKFIYAT, AVG(PRICE) AS ORTALAMAFIYAT
FROM SALES 


--AGGREGATE FUNC WHERE ÝLE KULLANIMI
--Mesela Ýstannbulda satýlan ürünlerimin ortalamasýný max min deðerlerini toplam ne kadar satýldýgýma bakalým

SELECT COUNT(*) TOPLAMADET, AVG(PRICE) FIYATORTALAMA, MAX(PRICE) ENYUKSEKFIYAT, MIN(PRICE) ENDUSUKFIYAT, SUM(PRICE) TOPLAMFIYAT

FROM SALES WHERE CITY='Ýstanbul'


--VEYA BÝR TARIH ARALIÐINA BAKALIM 
SELECT COUNT (PRICE) AS SATIRSAYISI,  SUM(TOTALPRICE) AS CÝRO, SUM(AMOUNT) AS TOPLAMADET, 
MIN(PRICE) AS ENDUSUKFIYAT, MAX(PRICE) AS ENYUKSEKFIYAT, AVG(PRICE) AS ORTALAMAFIYAT
FROM SALES  WHERE DATE_ BETWEEN '20190101' AND '20190131'



--VEYA BÝR ÞEHRE GÖRE BAKALIM 
SELECT COUNT (PRICE) AS SATIRSAYISI,  SUM(TOTALPRICE) AS CÝRO, SUM(AMOUNT) AS TOPLAMADET, 
MIN(PRICE) AS ENDUSUKFIYAT, MAX(PRICE) AS ENYUKSEKFIYAT, AVG(PRICE) AS ORTALAMAFIYAT
FROM SALES  WHERE CITY='ANKARA'


SELECT COUNT (PRICE) AS SATIRSAYISI,  SUM(TOTALPRICE) AS CÝRO, SUM(AMOUNT) AS TOPLAMADET, 
MIN(PRICE) AS ENDUSUKFIYAT, MAX(PRICE) AS ENYUKSEKFIYAT, AVG(PRICE) AS ORTALAMAFIYAT
FROM SALES  WHERE CITY='ÝSTANBUL'


