--------------TEMEL DDL(DATA DEFINITION LANGUAGE) KOMUTLARI-----------------------
--CREATE     ALTER     DROP
--SQL'de veritabaný þemasýný düzenlemek ve yönetmek için kullýlýr


-------CREATE---->VERÝ TABANINDA YENÝ BÝR TABLO OLUÞTURMAK ÝÇÝN KULLANILIR
CREATE TABLE CUSTOMERS2
(
ID INT IDENTITY(1,1) PRIMARY KEY, NAMESURNAME VARCHAR(100), TCNUMBER VARCHAR(13) NOT NULL, GENDER VARCHAR(1), 
EMAIL VARCHAR(100), BIRTHDATE DATE, CITY VARCHAR(50), DISTRICT VARCHAR(50), TELNR1 VARCHAR(15), TELNR2 VARCHAR(15)

)
--BURDA TABLO OLUÞTURULURKEN OTOMATÝK DEFAULT DEÐER OLARAK ALLOW NULL DEÐERÝ SEÇÝLÝ GELÝR. 
--EÐER BÝZ ONU SEÇMEZSEK BU DE DEMEK OLUYOR KÝ O ALANI BOÞ GEÇEMEZSÝN. MESELA TC KÝMLÝK BOÞ
--GEÇÝLEMEZ BÝR ALAN OLARAK KAYDEDERSEK VE VERÝ GÝRÝLMEZSE SÝSTEM KABUL ETMEYECEKTÝR

------------------------------------------------------------------------------------------------------------
------------       ALTER     ----------------------------------------------
--MEVCUT VERÝ TABANI NESNELERÝNÝ(TABLO ÝNDEX SUTUN) GÝBÝ DEÐERLERÝ GÜNCELLEMEK ÝÇÝN KULLANILIR
--MESELA YUKARIDA OLUÞTURDUÐUMUZ CUSTOMERS2 TABLOSUNA KOLON EKLEME ÝÞLEMLERÝ YAPALIM
ALTER TABLE CUSTOMERS2 ADD COUNTRY VARCHAR(50), AGE INT, AGEGROUP VARCHAR(50), TELOPERATOR1 VARCHAR(50)

--ÞÝMDÝ DE EKLEDÝÐÝMÝZ KOLONLARI SÝLELÝM
ALTER TABLE CUSTOMERS2 DROP COLUMN COUNTRY, AGE, AGEGROUP, TELOPERATOR1


--ÞÝMDÝ DE MEVCUT KOLONUN VERÝTÝPÝ BOYUTUNU DEÐÝÞTÝRELÝM. MESELA YUKARIDA GENDER VARCHAR(1) DEDÝK ONU 10 YAPALIM
ALTER TABLE CUSTOMERS2 ALTER COLUMN GENDER VARCHAR(10) 
--------------------------------------------------------------------------------------------------------

--------------    DROP   -------------------------------------------------------------------------------
--ÞÝMDÝ TEST ADINDA BÝR TABLO OLUÞTURALIM VE ÝÇÝNE BÝR KAÇ DEÐER ATALIM
CREATE TABLE TEST( ID INT IDENTITY(1,1), NAMESURNAME VARCHAR(100))

--ÝÇÝNE VERÝ EKLEME ÝÞLEMÝ YAPALIM
INSERT INTO TEST (NAMESURNAME) VALUES ('HASAN CAN')
SELECT * FROM TEST

--BUNU DELETE ÝLE SÝLERSEK ID ALANIMIZ TEKRARDAN VERÝ EKLEME ÝÞLEMÝNDE 2 DEN BAÞLAYACAKTIR
DELETE FROM TEST

--ÞÝMDÝ BUNU DROP ÝLE SÝLERSEK BU SEFER ID TEKRARDAN 1 DEN BAÞLAYACAKTIR

DROP TABLE TEST
-- BURDA DÝKKAT ETMEMÝZ GEREKÝYOR DROP TABLE KOMUTU TÜM TABLOYU SÝLER. ANCAK BÝZ BUNU TRUNCATE ÝLE SÝLSEYDÝK
--SADECE VERÝLERÝ SÝLECEKTÝ VE ID ALANINI DA 1 DEN BAÞLATACAKTI. DROP ÝLE ARASINDAKÝ FARK BUDUR

TRUNCATE TABLE TEST














