--------------DISTINCT KOMUTU----------------
--Bir SQL sorgusunda alýnan sonuç setindeki yinelenen deðerleri filtrelemek için kullanýlýr
SELECT * FROM CUSTOMERS

--MESELA KAÇ ADET UNIQUE YAÞ GRUBU VAR VEYA KAÇ ADET UNIQUE TELOPERATOR1 VAR BAKALIM
SELECT DISTINCT AGEGROUP FROM CUSTOMERS
SELECT DISTINCT TELOPERATOR1 FROM CUSTOMERS
SELECT DISTINCT GENDER FROM CUSTOMERS

-------------ORDER BY-----------------------------------
--Bu komut SQL de alýnan bir datayý belirli bir sýraya göre almak için kullanýlýr

SELECT * FROM CUSTOMERS
--AZDAN ÇOÐA DOÐRU BÝR SIRALAMA
SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME ASC

--ÇOKTAN AZA DOÐRU BÝR SIRALAMA
SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME DESC

--ÞÝMDÝ ÞEHRE GÖRE ALALIM VE AYNI ÞEHÝRLÝ OLANLARI DA ÝÝSM SIRASINA GÖRE ALALIM
SELECT * FROM CUSTOMERS ORDER BY CITY, NAMESURNAME 

--YADA ÝSME GÖRE ALALIM VE DOÐUM GÜNLERÝNÝN TERSÝBE GÖRE ALALIM
SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME, BIRHTDATE DESC

--ÖNCE ÝSTANBULU ALALIM VE ÞEHRE ÝLÇEYE VE CÝNSÝYETE GÖRE SEÇÝMÝ YAPALIM
SELECT * FROM CUSTOMERS WHERE CITY='ÝSTANBUL' ORDER BY CITY, DISTRICT, GENDER


--DAHA KARIÞIK VERÝSETLERÝNDE KOLON ÝSÝMLERÝ YAZMAK ZORLAYICI OLABÝLÝR. BUNUN DA KISA BÝR YOLU EÐER KAÇINCI
--KOLONDA OLDUÐUNU BÝLÝRSEK DÝREKT KOLON NUMARASI VEREREK DE ÇAÐIRMA ÝÞLEMÝ YAPILABÝLÝR. 
--MESELA (GENDER) KOLONU 4. SIRADA
SELECT * FROM CUSTOMERS ORDER BY 4

--YADA CITY(7) DISTRICT(8) VE GENDER(4) OLACAK ÞEKÝLDE ALABÝLÝRÝZ
SELECT * FROM CUSTOMERS ORDER BY 7, 8, 4


--------------TOP KOMUTU----------------------------
--SINIRLI BÝR SAYIDA VERÝ ALMAK ÝÇÝN KULLANILIR
--MESELA 10 ADET SATIR ALALIM VE ÝSÝMLERÝNE GÖRE AZALACAK ÞEKÝLDE SIRALAYARAK ALALIM
SELECT TOP 10 NAMESURNAME FROM CUSTOMERS ORDER BY NAMESURNAME DESC

--VEYA ÞEHRÝ ÝSTANBUL OLAN EN GENÇ 10 MÜÞTERÝYÝ ALALIM MESELA
SELECT TOP 10 * FROM CUSTOMERS WHERE CITY='ÝSTANBUL' ORDER BY BIRHTDATE DESC

--DAHA DA ÖZELLEÞTÝRELÝM. MESELA BU SEFERDE ÝSTANBUL VE CÝNSÝYETÝ ERKEK OLAN EN GEÇ MÜÞTERÝLERÝ ALALIM
SELECT TOP 10 * FROM CUSTOMERS WHERE CITY='ÝSTANBUL' AND GENDER='ERKEK' ORDER BY BIRHTDATE DESC

--TÜM TÜRKÝYEDEKÝ ERKEKLERÝN %20 SÝNÝ ALALIM
SELECT TOP 20 PERCENT * FROM CUSTOMERS WHERE GENDER='ERKEK'





