SELECT * FROM ADDRESS WHERE ID=1

DELETE FROM USERS WHERE ID=1
--BURDA SÝLME ÝÞLEMÝNÝ GERÇEKLEÞTÝRMEZ, ÇÜNKÜ TABLOLAR ARASINDA BÝR ÝLÝÞKÝ VAR BU ÝLÝÞKÝNÝN KORUNMASI ADINA
--SQL BU KOMUTA KOD ÝLÝÞKÝLERÝ ADINA SÝLMEZ
