--GROUP BY--
SELECT SUM(TOTALPRICE) CIRO FROM SALES WHERE CITY='ANKARA'

SELECT SUM(TOTALPRICE) CIRO FROM SALES WHERE CITY='ÝSTANBUL'


--ÞÝMDÝ TEK TEK BÖYLE ÞEHÝRLERÝ ALMAK YERÝNE BUNLARI TOPLU BÝR ÞEKÝLDE ALALIM

SELECT CITY AS SEHIR, SUM(TOTALPRICE) AS CIRO FROM SALES GROUP BY CITY ORDER BY SUM(TOTALPRICE) DESC
--BURADA ÞEHÝRLERE GÖRE EN FAZLA SATAN SIRADA OLMAK ÜZERE SEÇME ÝÞLEMÝ YAPTIK

--BAÞKA ÖRNEK MESELA BÖLGELERE VE O BÖLGEDE OLAN ÞEHÝRLERÝN TOPLAM SATIÞLARINA BAKALIM
SELECT REGION AS BOLGE, CITY AS SEHIR, SUM(TOTALPRICE) AS CIRO 
FROM SALES GROUP BY REGION, CITY ORDER BY REGION, CITY, SUM(TOTALPRICE)

--BÝR MAÐAZANIN GÜN BAZLI SATIÞINI GETÝRELÝM

SELECT  CONVERT(DATE, DATE_) AS TARIH , SUM(TOTALPRICE) AS CIRO 
FROM SALES WHERE CITY='ÝSTANBUL' GROUP BY CONVERT(DATE, DATE_) ORDER BY CONVERT(DATE, DATE_)
--CONVERT KOMUTU BÝR DEÐÝÞKENÝN VERÝ TÝPÝNÝ DEÐÝÞTÝRMEYE YARAR. DATE_ BIR DATETIME ÝDÝ ONU DATE OLARAK ALDIK


--BÝR GÜNÜN MAÐAZA BAZLI SATIÞLARINI GETÝRELÝM

SELECT CITY AS SEHIR, SUM(TOTALPRICE) AS CIRO
FROM SALES WHERE DATE_ BETWEEN '2019-08-02 00:00:00' AND '2019-08-08 23:59:59'
GROUP BY CITY 
ORDER BY SUM(TOTALPRICE) DESC

--BELÝRLÝ BÝR CIRONUN ÜZERÝNDE SATIÞ YAPAN MAÐAZALARI GETÝRME
SELECT CITY AS SEHIR, SUM(TOTALPRICE) AS CIRO
FROM SALES
GROUP BY CITY HAVING SUM(TOTALPRICE)>100000 
ORDER BY SUM(TOTALPRICE) DESC
--BURDA WHERE KULLANMAMAMIZIN NEDENÝ WHERE SADECE SATIR SATIR BAKAR ONA HERHANGÝ BÝR AGGREGATION VEREMEYIZ
--GROUP BY'DAN SONRA HAVING FONKSÝYONUNU KULLANIRIZ

--MAÐAZALARIN AYLARA GÖRE SATIÞINI GETÝRME ÝÞLEMÝÝ

SELECT CITY AS SEHIR, DATEPART(MONTH, DATE_) AS AY, SUM(TOTALPRICE) AS CIRO FROM SALES
GROUP BY CITY, DATEPART(MONTH, DATE_)
ORDER BY CITY, DATEPART(MONTH, DATE_)

--ÞÝMDÝ BUNLARI AYLARI SAYI OLARAK DEÐÝL DE ÝSÝM OLARAK ALALIM VE TÜRKÇE OLSUN 

SET LANGUAGE Turkish
SELECT CITY AS SEHIR, DATENAME(MONTH, DATE_) AS AY, SUM(TOTALPRICE) AS CIRO 
FROM SALES
GROUP BY CITY, DATENAME(MONTH, DATE_),DATEPART(MONTH, DATE_)
ORDER BY CITY, DATEPART(MONTH, DATE_)
--Burada önce dili türkçe olarak ayarladýk. Daha sonra þehri ve de aylarýn isimlerine göre kýrýlýma uðrayacak þekilde
--toplam fýyatý aldýk, Gruplama olarak da þehir ve ayý aldýk. Ay isimlerini datename fonksiyonu ile isme çevirdik
--order by ile de þehir ve ay isimlerine göre sýraladýk



--Ürün kategorilerine göre satýþlarý alalým

SELECT CATEGORY1 AS KATEGORÝ,CATEGORY2 AS KATEGORI2, SUM(TOTALPRICE) AS CIRO
FROM SALES
GROUP BY CATEGORY1, CATEGORY2 ORDER BY CATEGORY1, SUM(TOTALPRICE) DESC
--Bu komutda da kategori1 ve kategori2 ye göre gruplama iþlemi yaptýk ve toplam fýyata göre çaðýrýk.
--sýralama olarak da kategori1 e göre sýralý al ancak kategori2 de en fazla satýlan hangisi ise onu aldýk



--MAÐAZALARIN TEKÝL MÜÞTERÝ SAYILARINI GETÝRELÝM
SELECT CITY AS SEHIR, COUNT(DISTINCT CUSTOMERCODE) AS MUSTERI_SAYISI
FROM SALES
GROUP BY CITY ORDER BY CITY
---BURDA DISTINCT KULLANMASAYDIK MESELA AYNI MÜÞTERÝ BÝRDEN FAZLA ÜRÜN DE ALMIÞ OLABÝLÝR UNIQUE DEÐERLERÝ ALDIK SADECE


