--Arkadaşlar bu komutları kullanarak hazır bir e ticaret veri seti oluşturabilirsiniz

Create table USERS(
ID INT IDENTITY(1,1),
USERNAME_ VARCHAR(50),
PASSWORD_ VARCHAR(50),
NAMESURNAME VARCHAR(100),
EMAIL VARCHAR(100),
GENDER VARCHAR(1),
BIRTHDATE DATE,
CREATEDDATE DATETIME,
TELNR1 VARCHAR(15),
TELNR2 VARCHAR(15))


Create table ADDRESS(
ID INT IDENTITY(1,1),
USERID INT,
COUNTRYID TINYINT,
CITYID SMALLINT,
TOWNID INT,
DISTRICTID INT,
POSTALCODE VARCHAR(10),
ADDRESSTEXT VARCHAR(500))

Create table COUNTRIES(
ID TINYINT IDENTITY(1,1),
COUNTRY VARCHAR(50))

Create table CITIES(
ID SMALLINT IDENTITY(1,1),
COUNTRYID TINYINT,
CITY VARCHAR(50))

Create table TOWNS(
ID INT IDENTITY(1,1),
CITYID SMALLINT,
TOWN VARCHAR(50))

Create table DISTRICTS(
ID INT IDENTITY(1,1),
TOWNID INT,
DISTRICT VARCHAR(50))


Create table INVOICE(	
ID INT IDENTITY(1,1),	
ORDERID INT,	
DATE_ DATETIME,	
ADDRESSID INT,	
CARGOFICHENO VARCHAR(20),	
TOTALPRICE FLOAT)	
	
Create table INVOICEDETAIL(	
ID INT IDENTITY(1,1),	
INVOICEID INT,	
ORDERDETAILID INT,	
ITEMID INT,	
AMOUNT INT,	
UNITPRICE FLOAT,	
LINETOTAL FLOAT)	


Create table ORDERS(
ID INT IDENTITY(1,1),
USERID INT,
DATE_ DATETIME,
TOTALPRICE FLOAT,
STATUS_ TINYINT,
ADDRESSID INT)

Create table ORDERDETAILS(
ID INT IDENTITY(1,1),
ORDERID INT,
ITEMID INT,
AMOUNT INT,
UNITPRICE FLOAT,
LINETOTAL FLOAT)


Create table ITEMS(
ID INT IDENTITY(1,1),
ITEMCODE VARCHAR(50),
ITEMNAME VARCHAR(100),
UNITPRICE FLOAT,
CATEGORY1 VARCHAR(50),
CATEGORY2 VARCHAR(50),
CATEGORY3 VARCHAR(50),
CATEGORY4 VARCHAR(50),
BRAND VARCHAR(50))

Create table PAYMENTS(
ID INT IDENTITY(1,1),
ORDERID INT,
PAYMENTTYPE TINYINT,
DATE_ DATETIME,
ISOK BIT,
APPROVECODE VARCHAR(100),
PAYMENTTOTAL FLOAT)








