--WHERE KULLANIMI 

SELECT * FROM CUSTOMERS WHERE NAMESURNAME='ÖMER GÜLER'
SELECT * FROM CUSTOMERS WHERE GENDER='E'

--MESELA ÞÝMDÝ DE CÝNSÝYETÝ ERKEK OLMAYANLARI ALALIM. BUNU ÝKÝ ÞEKÝLDE YAPABÝLÝRÝZ
SELECT * FROM CUSTOMERS WHERE GENDER<>'E'
SELECT * FROM CUSTOMERS  WHERE NOT GENDER='E'

--WHERE ÞARTI BÜYÜK-KÜÇÜK
SELECT * FROM CUSTOMERS WHERE BIRHTDATE>'1990-01-01'
SELECT * FROM CUSTOMERS WHERE AGE <=50
SELECT * FROM CUSTOMERS WHERE NAMESURNAME>'Ý'

-- WHERE BETWEEN/IN OPERATÖRLERÝ
SELECT * FROM CUSTOMERS WHERE ID BETWEEN 2 AND 10
SELECT * FROM CUSTOMERS WHERE BIRHTDATE BETWEEN '1980-02-10' AND '2012-01-01'
SELECT * FROM CUSTOMERS WHERE CITY IN ('45','12','32')
SELECT * FROM CUSTOMERS WHERE ID IN(4,5,6,7)

-- LIKE OPERATÖRÜ
--BURDA SADECE ÝSMÝ ALÝ ÝLE BAÞLAYANLARI ALDIK
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE 'ALÝ%'

--BURDA DA ÝSMÝNÝN HERHANGÝ BÝR YERÝNDE ÝÇÝNDE ALÝ OLANI AL DEDÝK
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE '%ALÝ%'

--ÝSMÝ ALÝ ÝLE BÝTERÝ ALALIM
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE '%ALÝ'

--PEKÝ ÝKÝNCÝ ADI ALÝ OLANI NASIL ALABÝLÝRÝZ. BAKACAK OLURSAK ÝKÝNCÝ ADDAN ÖNCE BÝR BOÞLUK VE SONRA TEKRAR BÝR BOÞLUK VAR
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE '% ALÝ %'

--ÝKÝNCÝ ÝSMÝ ALÝ OLMAYANLARI ALDIK 
SELECT * FROM CUSTOMERS WHERE NAMESURNAME NOT LIKE '% ALÝ %'


-------------------UPDATE/DELETE KOMUTLARINDA WHERE ÞARTI KULLANIMI---------------------------------

SELECT * FROM CUSTOMERS 
--MESELA TABLOYA TEKRARDAN BÝR DEÐÝÞKEN EKLEYELÝM VE GÜNCELLEMEMÝZÝ YAPALIM
UPDATE CUSTOMERS SET AGEGROUP='61-90 YAÞ ARASI' WHERE AGE BETWEEN '61' AND '90'
--EVET BURADA 61 VE 90 YAÞ ARALIÐINDA OLAN KÝÞÝLERÝN YAÞLARINI AGEGROUP ÝÇERÝSÝNDE GÜNCELLEDÝK












